version: 2.1

templates:
  tagged-filter: &tagged-filter
    tags:
      only: /[0-9]+(\.[0-9]+)*/

executors:
  ubuntu-builder:
    docker:
      - image: trustlines/builder:master9
        environment:
          - SOLC_VERSION=v0.4.25
    working_directory: ~/repo

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  create-venv:
    description: "Create venv"
    steps:
      - run:
          name: Create python venv
          command: |
            python3 -m venv venv
            pip install -U pip wheel setuptools

  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo >> ${BASH_ENV} 'export PATH=~/bin:~/repo/venv/bin:${PATH}'
          echo >> ${BASH_ENV} '. ~/.nvm/nvm.sh'

  publish-npm:
    description: Publish npm package
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: Set authentication token
          command: |
            echo >> ~/.npmrc "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      - run:
          name: Set npm version
          command: |
            cd py-bin
            ./set_npm_version.sh
            cd ..
      - run:
          command: |
            cd py-bin
            npm publish --tag << parameters.tag >>

jobs:
  run-solium:
    executor: ubuntu-builder

    steps:
      - checkout
      - config-path
      - run:
          name: Install solium
          command: |
            npm install -g 'solium@>=1.0.9'
      - run:
          name: Run solium
          command: |
            solium  -f contracts/Destructable.sol -f contracts/Ownable.sol -f contracts/it_set_lib.sol -f contracts/TestItSet.sol
  install:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - restore_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
      - create-venv
      - run:
          name: Install requirements
          command: |
            pip install -c constraints.txt -r requirements.txt
      - save_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Verify installed packages have compatible dependencies
          command: |
            pip check
      - persist_to_workspace:
          root: "~"
          paths:
            - repo
  run-pytest:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run pytest
          command: |
            pytest tests

  run-flake8:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run flake8
          command: |
            flake8 tests

workflows:
  version: 2
  default:
    jobs:
      - run-solium:
          filters:
            <<: *tagged-filter
      - install:
          filters:
            <<: *tagged-filter
      - run-flake8:
          requires:
            - install
          filters:
            <<: *tagged-filter
      - run-pytest:
          requires:
            - install
          filters:
            <<: *tagged-filter
